[package]
name = "satsolver-kissat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
kissat = "0.1.0"
sicstus-rs = { path = "../../../sicstus-rs", version = "0.1.0" }
