#include <sicstus/sicstus.h>
/* ex_glue.h is generated by splfr from the foreign/[2,3] facts.
Always include the glue header in your foreign resource code.
*/
#include "ex_glue.h"

extern SP_integer c1(SP_integer a);
/* c1(+integer, [-integer]) */
/* SP_integer c1(SP_integer a) { return add(a, 9); } */
/* c2(-integer) */
void c2(SP_integer *a) { *a = 99; }
/* c11(+atom, [-atom]) */
SP_atom c11(SP_atom a) { return (a); }
/* c21(+atom, -atom) */
void c21(SP_atom a, SP_atom *b) { *b = a; }
/* c3(+float, [-float]) */
double c3(double a) { return (a + 9.0); }
/* c4(-float) */
void c4(double *a) { *a = 9.9; }
/* c5(string, [-string]) */
char const *c5(char const *a) { return (a); }
/* c6(-string) */
void c6(char const **a) { *a = "99"; }
