#include <sicstus/sicstus.h>
/* ex_glue.h is generated by splfr from the foreign/[2,3] facts.
Always include the glue header in your foreign resource code.
*/
#include "satsolver_glue.h"

extern void delete_solver(SP_integer id);
extern SP_integer new_solver();
extern void add_clause(SP_integer solver_id, SP_term_ref list);
extern void solve(SP_integer solver_id);
extern void get_model(SP_integer solver_id, SP_term_ref model);
extern void assign_model(SP_integer solver_id, SP_term_ref asgnList);
extern void toDimacs(SP_integer solver_id, char const *filename);
